"""initial schema

Revision ID: 8bd75904c5b9
Revises: 
Create Date: 2026-07-27 18:05:49.707762
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8bd75904c5b9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('libraries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('media_kind', sa.String(length=20), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('root_path', sa.String(length=2048), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_scan_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_libraries')),
    sa.UniqueConstraint('source_type', 'root_path', name='source_root')
    )
    with op.batch_alter_table('libraries', schema=None) as batch_op:
        batch_op.create_index('ix_libraries_enabled', ['enabled'], unique=False)

    op.create_table('media_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('library_id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('sort_title', sa.String(length=512), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('season_number', sa.Integer(), nullable=True),
    sa.Column('episode_number', sa.Integer(), nullable=True),
    sa.Column('external_source', sa.String(length=50), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('external_guid', sa.String(length=1024), nullable=True),
    sa.Column('poster_key', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], name=op.f('fk_media_items_library_id_libraries'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['media_items.id'], name=op.f('fk_media_items_parent_id_media_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_items')),
    sa.UniqueConstraint('library_id', 'external_source', 'external_id', name='external_identity')
    )
    with op.batch_alter_table('media_items', schema=None) as batch_op:
        batch_op.create_index('ix_media_items_library_type', ['library_id', 'item_type'], unique=False)
        batch_op.create_index('ix_media_items_parent_id', ['parent_id'], unique=False)
        batch_op.create_index('ix_media_items_title', ['title'], unique=False)

    op.create_table('scan_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('library_id', sa.String(length=36), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_relative_path', sa.String(length=4096), nullable=True),
    sa.Column('files_discovered', sa.Integer(), nullable=False),
    sa.Column('files_analyzed', sa.Integer(), nullable=False),
    sa.Column('files_skipped', sa.Integer(), nullable=False),
    sa.Column('files_failed', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('app_version', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], name=op.f('fk_scan_runs_library_id_libraries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scan_runs'))
    )
    with op.batch_alter_table('scan_runs', schema=None) as batch_op:
        batch_op.create_index('ix_scan_runs_library_status', ['library_id', 'status'], unique=False)
        batch_op.create_index('ix_scan_runs_started_at', ['started_at'], unique=False)

    op.create_table('media_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('media_item_id', sa.String(length=36), nullable=False),
    sa.Column('library_id', sa.String(length=36), nullable=False),
    sa.Column('relative_path', sa.String(length=4096), nullable=False),
    sa.Column('filename', sa.String(length=1024), nullable=False),
    sa.Column('version_label', sa.String(length=255), nullable=True),
    sa.Column('part_index', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('container', sa.String(length=50), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True),
    sa.Column('overall_bitrate', sa.BigInteger(), nullable=True),
    sa.Column('mtime_ns', sa.BigInteger(), nullable=False),
    sa.Column('quick_hash', sa.String(length=255), nullable=True),
    sa.Column('scan_status', sa.String(length=20), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], name=op.f('fk_media_files_library_id_libraries'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_item_id'], ['media_items.id'], name=op.f('fk_media_files_media_item_id_media_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_files')),
    sa.UniqueConstraint('library_id', 'relative_path', name='library_relative_path')
    )
    with op.batch_alter_table('media_files', schema=None) as batch_op:
        batch_op.create_index('ix_media_files_media_item_id', ['media_item_id'], unique=False)
        batch_op.create_index('ix_media_files_mtime_ns', ['mtime_ns'], unique=False)
        batch_op.create_index('ix_media_files_scan_status', ['scan_status'], unique=False)

    op.create_table('audio_streams',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('media_file_id', sa.String(length=36), nullable=False),
    sa.Column('stream_index', sa.Integer(), nullable=False),
    sa.Column('codec_name', sa.String(length=100), nullable=False),
    sa.Column('codec_profile', sa.String(length=255), nullable=True),
    sa.Column('channels', sa.Integer(), nullable=True),
    sa.Column('channel_layout', sa.String(length=100), nullable=True),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('bit_depth', sa.Integer(), nullable=True),
    sa.Column('bitrate', sa.BigInteger(), nullable=True),
    sa.Column('immersive_format', sa.String(length=30), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_forced', sa.Boolean(), nullable=False),
    sa.Column('is_commentary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['media_file_id'], ['media_files.id'], name=op.f('fk_audio_streams_media_file_id_media_files'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audio_streams')),
    sa.UniqueConstraint('media_file_id', 'stream_index', name='file_stream_index')
    )
    op.create_table('probe_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('media_file_id', sa.String(length=36), nullable=False),
    sa.Column('scan_run_id', sa.String(length=36), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('tool_version', sa.String(length=100), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['media_file_id'], ['media_files.id'], name=op.f('fk_probe_snapshots_media_file_id_media_files'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_run_id'], ['scan_runs.id'], name=op.f('fk_probe_snapshots_scan_run_id_scan_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_probe_snapshots'))
    )
    with op.batch_alter_table('probe_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_probe_snapshots_file_tool', ['media_file_id', 'tool_name'], unique=False)

    op.create_table('scan_file_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scan_run_id', sa.String(length=36), nullable=False),
    sa.Column('media_file_id', sa.String(length=36), nullable=True),
    sa.Column('relative_path', sa.String(length=4096), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('metadata_changed', sa.Boolean(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['media_file_id'], ['media_files.id'], name=op.f('fk_scan_file_results_media_file_id_media_files'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scan_run_id'], ['scan_runs.id'], name=op.f('fk_scan_file_results_scan_run_id_scan_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scan_file_results'))
    )
    with op.batch_alter_table('scan_file_results', schema=None) as batch_op:
        batch_op.create_index('ix_scan_file_results_run_status', ['scan_run_id', 'status'], unique=False)

    op.create_table('subtitle_streams',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('media_file_id', sa.String(length=36), nullable=False),
    sa.Column('stream_index', sa.Integer(), nullable=False),
    sa.Column('codec_name', sa.String(length=100), nullable=False),
    sa.Column('format_class', sa.String(length=20), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_forced', sa.Boolean(), nullable=False),
    sa.Column('is_hearing_impaired', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['media_file_id'], ['media_files.id'], name=op.f('fk_subtitle_streams_media_file_id_media_files'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subtitle_streams')),
    sa.UniqueConstraint('media_file_id', 'stream_index', name='file_stream_index')
    )
    op.create_table('video_streams',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('media_file_id', sa.String(length=36), nullable=False),
    sa.Column('stream_index', sa.Integer(), nullable=False),
    sa.Column('codec_name', sa.String(length=100), nullable=False),
    sa.Column('codec_profile', sa.String(length=255), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('pixel_format', sa.String(length=100), nullable=True),
    sa.Column('bit_depth', sa.Integer(), nullable=True),
    sa.Column('bitrate', sa.BigInteger(), nullable=True),
    sa.Column('frame_rate_num', sa.Integer(), nullable=True),
    sa.Column('frame_rate_den', sa.Integer(), nullable=True),
    sa.Column('color_primaries', sa.String(length=100), nullable=True),
    sa.Column('color_transfer', sa.String(length=100), nullable=True),
    sa.Column('color_matrix', sa.String(length=100), nullable=True),
    sa.Column('base_hdr_format', sa.String(length=20), nullable=False),
    sa.Column('has_hdr10_plus', sa.Boolean(), nullable=False),
    sa.Column('has_dolby_vision', sa.Boolean(), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_forced', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['media_file_id'], ['media_files.id'], name=op.f('fk_video_streams_media_file_id_media_files'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_video_streams')),
    sa.UniqueConstraint('media_file_id', 'stream_index', name='file_stream_index')
    )
    op.create_table('dolby_vision_metadata',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('video_stream_id', sa.String(length=36), nullable=False),
    sa.Column('profile', sa.String(length=20), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('compatibility_id', sa.Integer(), nullable=True),
    sa.Column('bl_present', sa.Boolean(), nullable=False),
    sa.Column('el_present', sa.Boolean(), nullable=False),
    sa.Column('rpu_present', sa.Boolean(), nullable=False),
    sa.Column('el_type', sa.String(length=20), nullable=False),
    sa.Column('detected_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['video_stream_id'], ['video_streams.id'], name=op.f('fk_dolby_vision_metadata_video_stream_id_video_streams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dolby_vision_metadata')),
    sa.UniqueConstraint('video_stream_id', name='video_stream')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dolby_vision_metadata')
    op.drop_table('video_streams')
    op.drop_table('subtitle_streams')
    with op.batch_alter_table('scan_file_results', schema=None) as batch_op:
        batch_op.drop_index('ix_scan_file_results_run_status')

    op.drop_table('scan_file_results')
    with op.batch_alter_table('probe_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_probe_snapshots_file_tool')

    op.drop_table('probe_snapshots')
    op.drop_table('audio_streams')
    with op.batch_alter_table('media_files', schema=None) as batch_op:
        batch_op.drop_index('ix_media_files_scan_status')
        batch_op.drop_index('ix_media_files_mtime_ns')
        batch_op.drop_index('ix_media_files_media_item_id')

    op.drop_table('media_files')
    with op.batch_alter_table('scan_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_scan_runs_started_at')
        batch_op.drop_index('ix_scan_runs_library_status')

    op.drop_table('scan_runs')
    with op.batch_alter_table('media_items', schema=None) as batch_op:
        batch_op.drop_index('ix_media_items_title')
        batch_op.drop_index('ix_media_items_parent_id')
        batch_op.drop_index('ix_media_items_library_type')

    op.drop_table('media_items')
    with op.batch_alter_table('libraries', schema=None) as batch_op:
        batch_op.drop_index('ix_libraries_enabled')

    op.drop_table('libraries')
    # ### end Alembic commands ###
